name: Node CI
on:
  - push

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: make install
      - run: make build
      - run: make lint